host: localhost
port: 8000
script-dir: scripts
proxies:
ssl:
  enabled: true
  certificate: server.crt
  key: server.key

pubs:
  example:
    script: example.sh
    token-hash: $2a$14$FucMWBg5wjVCcsz6cHmj2e9NpiqmkYbTEIjGa.U6.SH4CHj36St7q # example-token
